### ISSUE TITLE
Request to migrate to Basho Labs account

### ISSUE THREAD

**Issue by mjbrender** [basho/puppet-riak#47]
This project is great and I see it as a definite help to the community. Looking at the open issues, it's not clear whether the repo is run by engineering or is a "best effort" project. If it is best effort, I'd like to make it part of an effort to leverage the Basho Labs account and teams that we're building out on that account to get further contribution. 

For more info, see the public conversation on strategy here: https://github.com/basho-labs/the-riak-community/blob/master/config-mgmt-strategy.md

**Comment by mjbrender** [comment]
Hey @haf, will this migration hurt any of your tooling or links? I need to move forward soon  and I'd like to respect your huge contribution here!

**Comment by haf** [comment]
Hi @mjbrender 

Thank you for your consideration. I think you're onto something good here and I think you should go ahead!

Thanks for the heads up! Will you add me to the new org?

**Comment by haf** [comment]
By the way; it's probably best-effort, but I merge and quality check everything going into it.

**Comment by mjbrender** [comment]
Hi @haf - it's great to meet you and have your contribution going forward. Yes, I'll add you to a team that has read/write over Puppet right after migration. We'll also have a few others who are interested to help and I look forward to introducing everyone. 

Migrating! :shipit:
